# This is a sample config for anipy-cli

# If you start the program for the first time the
# config file gets created automatically

# Place of the config:
# Linux: ~/.config/anipy-cli/config.yaml
# Windows: %USERPROFILE%/AppData/Local/anipy-cli/config.yaml
# MacOS: ~/.config/anipy-cli/config.yaml

# Folder where downloaded Anime go
# Default: anipy_install_path/download
# Note: Windows paths also work
download_folder_path: "~/anipy-cli/downloads/common"

# Folder where Seasonal Anime dls go
# Default: anipy_install_path/download/seasonals
seasonals_dl_path: "~/anipy-cli/downloads/seasonals"

# Folder where history, logs etc. go
# Default: anipy_install_path/user_files
user_files_path: "~/anipy-cli/user_files"

# Url of the goganime website, only change if needed
gogoanime_url: "https://gogoanime.gg/"

# Path to the video-player.
# Supported Players are: mpv, vlc, syncplay, mpvnet
# Default: mpv
player_path: "mpv"

# Specify additional mpv/vlc options (syncplay uses the same options as mpv)
# every command should be wrappedd in quotes (').
# Look here for various commands:
#   - mpv: https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst
#   - vlc: https://wiki.videolan.org/VLC_command-line_help/
mpv_commandline_options:
  - "--fs"
  - "--cache"

# here the options are left empty, but you could also just remove the whole line
vlc_commandline_options: []

# Reuse the mpv window instead of closing and reopening.
# This uses python-mpv, which uses libmpv, on linux this is preinstalled
# with mpv, on windows you have to get the mpv-2.dll file from here:
# https://sourceforge.net/projects/mpv-player-windows/files/libmpv/
# Default: False
reuse_mpv_window: False

# Always use ffmpeg to download hls streams, you can
# also activate this temporarily using the -f flag when
# downloading something.
# Default: False
ffmpeg_hls: False

# This determines how downloaded anime will be named
# The following variables can be used: show_name, episode_number, quality
# Default: '{show_name}_{episode_number}.mp4'
download_name_format: "{show_name} - {episode_number} - {quality}.mp4"

# This removes the (Dub) in the anime title when downloading
# Default: False
download_remove_dub_from_folder_name: True

# Discord Presence:
# Show what you are watching on discord
# Default: False
dc_presence: False

# When finishing downloading a video
# with the menu option in the default mode (cli)
# automatically open it with mpv.
auto_open_dl_defaultcli: False

# Mal user credentials
# Required to connect to your MAL account and use the MAL cli.
mal_user: username
mal_password: password

# Specify Anime Types that should be shown in search results.
# Defaults to sub and dub
anime_types: 
  - "sub"
  - "dub"
